version: "3.9"

services:
  questdb:
    image: questdb/questdb
    container_name: questdb_quickstart
    restart: always
    ports:
      - "18812:8812"
      - "19000:9000"
      - "19009:9009"
      - "19003:9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss
    container_name: questdb_quickstart_grafana
    restart: always
    ports:
      - 13000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dashboard/grafana/home_dir/var_lib_grafana:/var/lib/grafana/
      - ./dashboard/grafana/home_dir/etc_grafana:/etc/grafana/
    environment:
      - QDB_CLIENT_HOST=${QDB_CLIENT_HOST:-host.docker.internal}
      - QDB_CLIENT_PORT=${QDB_CLIENT_PORT:-18812}
      - QDB_CLIENT_PG_USER=${QDB_CLIENT_PG_USER:-admin}
      - QDB_CLIENT_PG_PASSWORD=${QDB_CLIENT_PG_PASSWORD:-quest}
      # use the value "disable" for local installations, and "require" for QuestDB Cloud
      - QDB_SSL_PG_MODE=${QDB_SSL_PG_MODE:-disable}

  ilp_ingestion:
    build: ./ingestion/python/tsbs_send
    container_name: questdb_quickstart_ingestion
    depends_on:
      - questdb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - QDB_CLIENT_HOST=${QDB_CLIENT_HOST:-host.docker.internal}
      - QDB_CLIENT_PORT=${QDB_CLIENT_PORT:-19009}
      - QDB_CLIENT_TLS=${QDB_CLIENT_TLS:-False}
      - QDB_CLIENT_AUTH_KID=${QDB_CLIENT_AUTH_KID:-}
      - QDB_CLIENT_AUTH_D=${QDB_CLIENT_AUTH_D:-}
      - QDB_CLIENT_AUTH_X=${QDB_CLIENT_AUTH_X:-}
      - QDB_CLIENT_AUTH_Y=${QDB_CLIENT_AUTH_Y:-}



